### ISSUE TITLE
FeatureRequest: none-interactive conversation mode 

### ISSUE THREAD

**Issue by Cyborgscode** [reorx/ai.py#6]
"none-interactive conversation mode" I guess you can imagine what i mean, for everyone else reading it:

"-c" enabled conversation mode, where all previous communication is send as history, so chat.ai can understand the context of a rephrased sentence.  This only works in interactive mode inside ai.py.

here is the request:

if a "Prompt" and option "-c" are given together, accept a "history"-file ( in the 90s we called it a brainfile ) as a third argument and send it with the prompt to the API. For better parsing I suggest an ordered JSON String-Array [ sortorder: oldest first ]. 

This would allow external code to get better results via ai.py .

**Comment by reorx** [comment]
Good idea. Additional thoughts:
- we don't need to call it "conversation mode" since using a history file is already conversational.
- name this argument `--history`, the usage would be like `ai --history /path/to/history.json <other args>`, if an additional `-w` is added, the history.json would be updated with the new messages input and generated in this call
- the content of`history.json` would be the dump of `ChatSession.messages` which is an array of dict items

Should be implemented in a day or two

**Comment by Cyborgscode** [comment]
ChatGPT via ai.py is now implemented in 3 modes of work "FreeTalk" : talk to it like a human, "Keyword": react only if a certain word is used and as "GapFiller": helping out with a reaction in case no local result is processed.

**Comment by reorx** [comment]
I made it, but after further consideration, I didn't make `--history` to imply conversation mode, so `-c` is still needed to achieve your requirement. See the example below:

```
ai --history history.json -w -c 'remeber that a = 1, I will ask you later'
Sure, I'll be here. Feel free to ask me anything you need help with later on.

ai --history history.json -w -c 'what is a + 2 in short?'
a + 2 is equal to 3 since a was previously defined as 1.
```

history.json after running the two commands:
```
[
  {
    "role": "user",
    "content": "remeber that a = 1, I will ask you later"
  },
  {
    "role": "assistant",
    "content": "Sure, I'll be here. Feel free to ask me anything you need help with later on."
  },
  {
    "role": "user",
    "content": "what is a + 2 in short?"
  },
  {
    "role": "assistant",
    "content": "a + 2 is equal to 3 since a was previously defined as 1."
  }
]
```

**Comment by Cyborgscode** [comment]
and how does the script know, which role it should use?

**Comment by Cyborgscode** [comment]
ahh ok, forget the question.

**Comment by Cyborgscode** [comment]
works like a charm :D
