### ISSUE TITLE
FR: move config file to $HOME/.config/ instead of $HOME

### ISSUE THREAD

**Issue by Cyborgscode** [reorx/ai.py#7]
having the homedir full of hidden directories and files, everyone should place theire files to the correct directories according to the FreeDesktop doctrine (!=Windows ofcourse) . 

In this case, it would be $HOME/.config/ 

OR accept an ENV variable with the API key and do not require a single-line-configfile ;)

**Comment by reorx** [comment]
Will do. I really should have followed this standard, since I have known it for many years, which I remembered as XDG directories.

**Comment by reorx** [comment]
Actually, the env var is supported, did I forget to mention it? You can use `AI_PY_API_KEY` which has a higher priority than the config file.

**Comment by Cyborgscode** [comment]
maybe i have overlooked the ENV variable.
